// This file is automatically generated. Do not edit it directly.
// Powered by EnterCloud Managed Supabase
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spb-t4nv7v8lc2v8ud5v.supabase.opentrust.net";
const SUPABASE_PUBLISHABLE_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiYW5vbiIsInJlZiI6InNwYi10NG52N3Y4bGMydjh1ZDV2IiwiaXNzIjoic3VwYWJhc2UiLCJpYXQiOjE3ODA5MjgzNjMsImV4cCI6MjA5NjUwNDM2M30.Cq-5TekoeOn6E00EPR4KKkTldctRN2GR-ozBnB3CP1k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
